apiVersion: v1
kind: Namespace
metadata:
  name: image-preloader
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: image-preloader
provisioner: bsu.csi.outscale.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-preloader-pvc
  namespace: image-preloader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: image-preloader
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: image-preloader
driver: bsu.csi.outscale.com
deletionPolicy: Delete
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-preloader-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update", "patch", "create"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-preloader-sa
  namespace: image-preloader
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-preloader-binding
subjects:
  - kind: ServiceAccount
    name: image-preloader-sa
    namespace: image-preloader
roleRef:
  kind: ClusterRole
  name: image-preloader-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: image-preloader
  namespace: image-preloader
spec:
  template:
    spec:
      serviceAccountName: image-preloader-sa
      containers:
      - name: image-preloader
        image: PRELOADER_IMAGE
        securityContext:
          privileged: true
          runAsUser: 0
        command: ["/snapshot.sh"]
        env:
        - name: COPY_TO
          value: /snapshot
        - name: SNAPSHOT_NAME
          value: image-preloader-snap
        - name: SNAPSHOT_CLASS
          value: image-preloader
        - name: SNAPSHOT_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PVC_NAME
          value: image-preloader-pvc
        volumeMounts:
        - mountPath: "/snapshot"
          name: image-preloader-volume
        - mountPath: /var/run/containerd/containerd.sock
          name: containerd-sock
        - mountPath: "/var/lib/containerd"
          name: containerd-directory
        - mountPath: "/tmp"
          name: tmp-directory
        - mountPath: "/usr/local/bin"
          name: local-bin-directory
          readOnly: true
      volumes:
        - name: image-preloader-volume
          persistentVolumeClaim:
            claimName: image-preloader-pvc
        - name: containerd-sock
          hostPath:
            path: "/var/run/containerd/containerd.sock"
        - name: containerd-directory
          hostPath:
            path: "/var/lib/docker"
        - name: local-bin-directory
          hostPath:
            path: "/usr/local/bin"
        - name: tmp-directory
          hostPath:
            path: "/tmp"
      restartPolicy: Never
  backoffLimit: 2