# Github action for releasing the binaries
name: release

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:  

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Get changelog for release
        id: changelog
        uses: mindsers/changelog-reader-action@1faaf50aa09d5793d9a100819973df801febfb31 # v2
        with:
          path: "CHANGELOG.md"
          version: ${{ github.ref_name }}
      - name: Create Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          body: ${{ steps.changelog.outputs.changes }}
